    Q48. Write the NumPy program to create a 2d array with 6 on the border and 0 inside?

In [9]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


    Q49. Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern?

In [10]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


    Q50. Write the NumPy program to create an empty and a full array.

In [14]:
import numpy as np

x=np.empty((3,4))
x=np.full((3,3),6)
print(x)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


    Q51. Write the NumPy program to convert the values of Centigradedegrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array.

In [2]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


    Q52. Write the NumPy program to find the real and imaginary parts of an array of complex numbers?

In [8]:
import numpy as np
values=[1.00000000+0.j,0.70710678+0.70710678j]
x=np.array(values)
real_x=x.real
imaginary_x=x.imag
print("Real Part {} ".format(real_x))
print("Imaginary Part {} ".format(imaginary_x))


Real Part [1.         0.70710678] 
Imaginary Part [0.         0.70710678] 


    Q53. Write the NumPy program to test whether each element of a 1-D array is also present in the second array?

In [14]:
import numpy as np
x1=[0,10,20,40,60]
x2= [0,40]
x1_ar=np.array(x1)
x2_ar=np.array(x2)
print(x1_ar)
print(np.in1d(x1_ar,x2_ar))

[ 0 10 20 40 60]
[ True False False  True False]


    Q54. Write the NumPy program to find common values between two arrays?

In [18]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


    Q55. Write the NumPy program to get the unique elements of an array?

In [22]:
import numpy as np
x=np.array([10,10,20,20,30,30])
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print(np.unique(x))

[10 20 30]
[1 2 3]


    Q56.Write the NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays?

In [23]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


    Q57. Write the NumPy program to test if all elements in an array evaluate to True ?

In [24]:
import numpy as np

print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


    Q58 Write the NumPy program to test whether any array element along the given axis evaluates to True?

In [25]:
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

False
True
True
True


    Q59. Write the NumPy program to construct an array by repeating?

In [27]:
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x = np.tile(a, 2)
print(x)
print("Repeating 3 times")
x = np.tile(a, 3)
print(x)

Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]
Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


    Q60. Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array?

In [30]:
import numpy as np

x=[1,2,3,4,5,6]
array=np.array(x)
print("Maximum Values: ",np.argmax(array))
print("Minimum Values: ",np.argmin(array))

Maximum Values:  5
Minimum Values:  0


    Q61. Write the NumPy program compare two arrays using numpy?

In [31]:
import numpy as np

a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


    Q62. Write the NumPy program to sort an along the first, last axis of an array?

In [32]:
import numpy as np
a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


    Q63. Write the NumPy program to sort pairs of first name and last name return their indices (first by last name, then by first name).

In [1]:
import numpy as np

first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


    Q64. Write the NumPy program to get the values and indices of the elements that are bigger than 10 in the given array?

In [13]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


    Q65. Write the NumPy program to find the memory size of a NumPy array?

In [14]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


    Q66. Write the NumPy program to create an array of ones and an array of zeros?

In [15]:
import numpy as np
print("Create an array of zeros")
x = np.zeros((1,2))
print("Default type is float")
print(x)
print("Type changes to int")
x = np.zeros((1,2), dtype = np.int)
print(x)
print("Create an array of ones")
y= np.ones((1,2)) 
print("Default type is float")
print(y)
print("Type changes to int")
y = np.ones((1,2), dtype = np.int)
print(y)

Create an array of zeros
Default type is float
[[0. 0.]]
Type changes to int
[[0 0]]
Create an array of ones
Default type is float
[[1. 1.]]
Type changes to int
[[1 1]]


    Q67. Write the NumPy program to change the dimension of an array?

In [20]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
x.shape = (3, 3)
print(x)

Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


    Q68. Write the NumPy program to create a new shape to an array without changing its data ?

In [21]:
import numpy as np
r = np.arange(16)

print('original r: \n',r)
print('\nreshaped array: \n',r.reshape((4,4)))
print('\narray r after reshape was applied: \n',r)

original r: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

array r after reshape was applied: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


    Q69. Write the NumPy program to create a new array of 3*5, filled with 2?

In [29]:
import numpy as np

v=2#np.ones((1,3), dtype = np.int)
r=np.zeros((3,5),dtype=int)
t=r+2
#x = np.full((3, 5), 2, dtype=np.uint)
t

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

    Q70. Write the NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere?

In [30]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


    Q71. Write the NumPy program to split an array of 14 elements into the 3 arrays and each of which has 2, 4, and 8 elements in original order?

In [31]:
import numpy as np
x = np.arange(1, 15)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [2, 6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


    Q72. Write the NumPy program to split of an array of shape 4x4 it into two arrays along the second axis ?

In [35]:
import numpy as np

r=np.arange(16).reshape(4,4)
print("Original array : ",r)
result=np.split(r,2,axis=1)
print(result)

Original array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


    Q73. Write the NumPy program to create a 5x5 matrix with row values ranging from 0 to 4?

In [40]:
import numpy as np

r=np.zeros((5,5))
r+=np.arange(5)
r

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

    Q74. Write the NumPy program to create an array of zeros and three column types (integer, float, character)?

In [56]:
import numpy as np

r=np.zeros((3,),dtype=('i4,f4,a40'))
new_data=[(1.,2.,"Ajith"),(2.,2.,"lal"),(9.,4,"kk")]
r[:]=new_data
r

array([(1, 2., b'Ajith'), (2, 2., b'lal'), (9, 4., b'kk')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S40')])

    Q75. Write the NumPy program to remove the negative values in thenumpy array with 0?

In [63]:
import numpy as np
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x < 0] = 0
print(x)

Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]
